---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authcore
  namespace: luna-wangpc-dev
spec:
  selector:
    matchLabels:
      app: authcore
  replicas: 1
  template:
    metadata:
      labels:
        app: authcore
    spec:
      containers:
        - name: authcore
          image: 192.168.10.104:4800/luna-wangpc-dev/authcore:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ENV_JVM_FLAGS
              valueFrom:
                configMapKeyRef:
                  name: java-common-config
                  key: ENV_JVM_FLAGS
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: skywalking-server:11800
          volumeMounts:
            - mountPath: /root/luna/logs
              name: logdata
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "500Mi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            failureThreshold: 5
            periodSeconds: 10
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.16.0
          args: [
            "-c", "/opt/filebeat/filebeat.yml",
            "-e"
          ]
          volumeMounts:
            - mountPath: /opt/filebeat/
              name: config
            - mountPath: /root/luna/logs
              name: logdata
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "500Mi"
      volumes:
        - name: logdata
          emptyDir: { }
        - name: config
          configMap:
            name: filebeat
            items:
              - key: filebeat.yml
                path: filebeat.yml
