---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat
  namespace: luna-wangpc-dev
data:
  holder: "占位符"
  filebeat.yml: |-
   filebeat.inputs:
     - type: log
       enabled: true
       paths:
         - /root/luna/logs/*/*/*/*filebeat*.log
       json.keys_under_root: true
       json.overwrite_keys: true
   setup.ilm.enabled: false
   setup.template.name: "my-log"
   setup.template.pattern: "my-log-*"


   filebeat.config.modules:

     path: ${path.config}/modules.d/*.yml


     reload.enabled: false



   setup.template.settings:
     index.number_of_shards: 1

   setup.kibana:

   output.elasticsearch:
     hosts: ["192.168.10.104:9200"]

     index: "my-log-%{+yyyy.MM.dd}"

   processors:
     - add_host_metadata:
         when.not.contains.tags: forwarded
     - add_cloud_metadata: ~
     - add_docker_metadata: ~
     - add_kubernetes_metadata: ~


