---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: luna-wangpc-dev
  labels:
    app: gateway
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: gateway
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  namespace: luna-wangpc-dev
spec:
  rules:
    - host: "gateway.luna-wangpc-dev.wangpc.fingard.vm"
      http:
        paths:
          - backend:
              service:
                name: gateway
                port:
                  number: 8080
            path: /
            pathType: Prefix

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: luna-wangpc-dev
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 192.168.10.104:4800/luna-wangpc-dev/gateway:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ENV_JVM_FLAGS
              valueFrom:
                configMapKeyRef:
                  name: java-common-config
                  key: ENV_JVM_FLAGS
            - name: BK_SERVICE
              value: 192.168.10.104:11800
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: skywalking-server:11800
          volumeMounts:
            - mountPath: /root/luna/logs
              name: logdata
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "500Mi"
          # 启动状态检查
          readinessProbe:
            # 检查tcp端口
            tcpSocket:
              port: 8080
            # 首次检查等待时间
            initialDelaySeconds: 5
            # 检查多少次
            failureThreshold: 5
            # 检查时间间隔
            periodSeconds: 10
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.16.0
          args: [
            "-c", "/opt/filebeat/filebeat.yml",
            "-e"
          ]
#          env:
#            - name: POD_IP
#              valueFrom:
#                fieldRef:
#                  fieldPath: status.podIP
#                  apiVersion: v1
#            - name: pod_name
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name
#                  apiVersion: v1
          volumeMounts:
            - mountPath: /opt/filebeat/
              name: config
            - mountPath: /root/luna/logs
              name: logdata
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "500Mi"
      volumes:
        - name: logdata
          emptyDir: {}
        - name: config
          configMap:
            name: filebeat
            items:
              - key: filebeat.yml
                path: filebeat.yml
