---
apiVersion: v1
kind: ConfigMap
metadata:
  name: java-common-config
  namespace: luna-wangpc-dev
data:
  holder: "占位符"
  ENV_JVM_FLAGS: >-
    -Dspring.cloud.nacos.server-addr=nacos.luna-wangpc-dev:8848
    -Dspring.cloud.nacos.username=nacos
    -Dspring.cloud.nacos.password=nacos
    -Dspring.cloud.nacos.config.group=1.3
    -Dspring.cloud.nacos.config.shared-configs[0].data-id=PUBLIC-COMMON.properties
    -Dspring.cloud.nacos.config.shared-configs[0].refresh=false
    -Dspring.cloud.nacos.config.shared-configs[0].group=1.3
    -Dspring.cloud.nacos.discovery.namespace=luna-wangpc-dev
    -Dspring.cloud.nacos.config.namespace=luna-wangpc-dev
    -Dluna.framework.starter.configcenter.nacos.enable=true
