---
apiVersion: v1
kind: ConfigMap
metadata:
  name: java-common-config
data:
  TZ: "Asia/Shanghai"
  ENV_JVM_FLAGS: {{ $.Values.global.javaEnvJvmFlags }}
  ENV_SKYWALKING_AGENT: {{$.Values.global.envSkywalkingAgent}}
