---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  namespace: {{$.Values.kibana.namespace}}
data:
  holder: "占位符"
  kibana.yml: |-
    server.host: "0.0.0.0"
    elasticsearch.hosts: [ "http://192.168.10.104:9200" ]
    i18n.locale: "zh-CN"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{$.Values.kibana.namespace}}
spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 15601
      name: kibana
  selector:
    app: kibana
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: {{$.Values.kibana.namespace}}
spec:
  rules:
    - host: "kibana.luna-wangpc-dev.wangpc.fingard.vm"
      http:
        paths:
          - backend:
              service:
                name: kibana
                port:
                  number: 5601
            path: /
            pathType: Prefix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{$.Values.kibana.namespace}}
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          {{- with $.Values.kibana}}
          image: {{ .image }}:{{ .version }}
          {{- end }}
          ports:
            - containerPort: 5601
              name: http
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            requests:
              memory: "1000Mi"
            limits:
              memory: "1000Mi"
          readinessProbe:
            tcpSocket:
              port: 5601
            initialDelaySeconds: 5
            failureThreshold: 5
            periodSeconds: 10
          volumeMounts:
            - mountPath: /usr/share/kibana/config/kibana.yml
              name: config
              subPath: kibana.yml
      volumes:
        - name: config
          configMap:
            name: kibana

