{{ if $.Values.redis.enable }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 16379
  selector:
    app: redis

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        version: v1
    spec:
      containers:
        - name: redis
          {{- with $.Values.redis}}
          image: {{ .image }}:{{ .version }}
          {{- end }}
          resources:
            requests:
              memory: "300Mi"
            limits:
              memory: "300Mi"
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /var/lib/redis
      volumes:
        - name: redis-data
          emptyDir: {}

{{end}}
